# fly.toml app configuration file generated for christmas-draw on 2025-11-19T18:45:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'christmas-draw'
primary_region = 'sin'

[build]
  dockerfile = "DockerFile"

[env]
  PORT = "5000"
  PYTHONUNBUFFERED = "1" 

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "christmas_draw_data"
  destination = "/data"